type StudyModule = { title: string; summary: string; topics: string[]; view?: string };

export const learningHub = 'https://dandy-macaroon-c7c.notion.site/2dea49695fb8808a89ccd95b93eb216b';

// Public Notion views checked on 2026-09-15. Mixed views containing internal
// project or server notes deliberately have no public link here.
export const studyModules: Record<string, StudyModule[]> = {
  'semester-1': [
    { title: 'Mathematik 1 · Lineare Algebra', summary: 'Von Aussagen und Beweisen zu Vektoren und Matrizen: Meine Notizen verbinden die mathematischen Grundlagen mit konkreten Rechenaufgaben und typischen Fehlern beim Lösen von Gleichungssystemen.', topics: ['Mengen, Aussagenlogik und Beweisverfahren', 'Gruppen, Ringe, Körper und komplexe Zahlen', 'Gauß-Verfahren, Determinanten und Rang', 'Eigenvektoren, Linearkombinationen und Basiswechsel'], view: '356a49695fb880aa8a87000c0cf7a27e' },
    { title: 'Web Engineering 1', summary: 'Wie gelangt eine Seite vom Server in den Browser? Dazu habe ich Netzwerkgrundlagen, Seitenaufbau und JavaScript bearbeitet. Eigene Webseiten und ein Kontaktformular machen die Konzepte praktisch greifbar.', topics: ['HTTP, DNS, URLs und Client-Server-Modell', 'HTML, CSS-Selektoren, DOM und Ebenen mit z-index', 'JavaScript, Web-APIs, Promises und async/await', 'Einstieg in Node.js und Express'], view: '356a49695fb880c48ab1000c4a8959b2' },
    { title: 'Programmieren 1 · Python', summary: 'Vom ersten Datentyp zur Objektorientierung: In meinem textbasierten Dungeon-Spiel sind Spieler, Monster und Räume als Klassen organisiert. Dazu kommen Übungen und eine Bibliotheksverwaltung.', topics: ['Variablen, Zahlen, Strings und Funktionen', 'Bedingungen, Schleifen, Listen, Tupel und Dictionaries', 'Klassen, Objekte und Konstruktoren', 'Dungeon-Spiel, Tests und dokumentierte Codefehler'], view: '356a49695fb880229df7000cb210de55' },
    { title: 'Elektrotechnik', summary: 'Die physikalische Seite der Informatik: Ich habe elektrische Größen, Bauteile und Schaltungen bearbeitet und mit Rechenaufgaben, Lernkarten und Probeklausuren vertieft.', topics: ['Strom, Spannung, Widerstand und elektrische Leistung', 'Gleichstromschaltungen, Kondensatoren und Spulen', 'Magnetfelder, Induktion und Transformatoren', 'Wechselstrom, Filter, Messtechnik und Analog-Digital-Wandlung'], view: '356a49695fb8800d97ec000c5848ec39' },
    { title: 'Theoretische Informatik', summary: 'Hier geht es um präzises Beschreiben und Begründen. Meine Sammlung reicht von Aussagen- und Prädikatenlogik über Prolog und Verschlüsselung bis zur Analyse von Algorithmen.', topics: ['Logik, Quantoren und algebraische Strukturen', 'Prolog: Fakten, Regeln und Abfragen', 'RSA und Diffie-Hellman als Lernbeispiele', 'Rekursion, Laufzeitschranken und Heaps'], view: '356a49695fb880d1b7b1000cac50a839' },
    { title: 'Schlüsselqualifikationen · BWL', summary: 'Technische Projekte stehen in einem wirtschaftlichen Umfeld. In diesem Modul habe ich Unternehmensformen sowie Methoden zur Standort-, Branchen- und Strategieanalyse gesammelt.', topics: ['Grundlagen des Wirtschaftens', 'Einzelunternehmen, GbR und GmbH', 'Standortfaktoren und PESTEL-Analyse', 'Porters Wettbewerbskräfte und Wettbewerbsstrategien'], view: '356a49695fb880b5b8fc000c268ae733' },
    { title: 'Anwendungsprojekt · Grundlagen', summary: 'Die frühen Projektnotizen beschäftigen sich mit Zusammenarbeit und dem Umgang mit Veränderungen. Dokumentiert sind ein erstes Meeting, Agilität, VUCA und die Rolle des Scrum Masters.', topics: ['Projektauftakt und Abstimmung', 'Agiles Arbeiten und Scrum', 'VUCA: mit Unsicherheit und Veränderung umgehen'] },
  ],
  'semester-2': [
    { title: 'Mathematik 2 · Analysis', summary: 'Der bisher dokumentierte Schwerpunkt ist der Aufbau der Zahlenbereiche: Wie entstehen aus natürlichen Zahlen ganze, rationale und schließlich reelle Zahlen? Die Lernseite führt diesen Weg mit Axiomen, Induktion und Äquivalenzklassen her.', topics: ['Peano-Axiome und vollständige Induktion', 'Rechenregeln und Ordnung auf den natürlichen Zahlen', 'Konstruktion ganzer und rationaler Zahlen', 'Cauchy-Folgen und Vollständigkeit der reellen Zahlen'], view: '359a49695fb8805184c7000cfcfff639' },
    { title: 'Web Engineering 2', summary: 'Im Lern-Hub ist eine AI Prompt Library als Webprojekt mit FastAPI und SQLite dokumentiert. Ein Vergleich mit einem PocketBase-Projekt ergänzt die Beschäftigung mit verschiedenen Backend-Ansätzen.', topics: ['AI Prompt Library als Webprojekt', 'FastAPI und SQLite', 'Vergleich von Backend-Ansätzen'] },
    { title: 'Algorithmen & Komplexität', summary: 'Algorithmen Schritt für Schritt nachvollziehen, ihre Korrektheit begründen und Laufzeiten vergleichen: Dazu habe ich Pseudocode, Trockenläufe und zahlreiche Übungsaufgaben gesammelt.', topics: ['InsertionSort, MergeSort, QuickSort, HeapSort und lineare Sortierverfahren', 'Schleifeninvarianten, Rekursionsgleichungen und Master-Theorem', 'Hashing, Prioritätswarteschlangen und binäre Suchbäume', 'Breiten- und Tiefensuche, topologische Sortierung und Dijkstra'], view: '359a49695fb880ac8d14000cb29a80d7' },
    { title: 'Praktische Datenverarbeitung', summary: 'Die fachlichen Notizen drehen sich um Netzwerke und die Arbeit in der Kommandozeile: IP-Adressen verstehen, Dateien finden und Zugriffsrechte setzen.', topics: ['TCP/IP und Aufbau von IPv4-Adressen', 'Bits, Oktette sowie Netz- und Hostanteil', 'Routing, DHCP und NAT', 'Bash: ls, grep und chmod'] },
    { title: 'Anwendungsprojekt · Weiterführung', summary: 'Die Projektansicht verbindet Notizen aus mehreren Phasen. Als fachlicher Einblick bleiben die Grundlagen agiler Zusammenarbeit und die Beschäftigung mit Schnittstellen; ein eigenständiger Rückblick auf das zweite Semester ist dort noch nicht ausgearbeitet.', topics: ['Agile Zusammenarbeit', 'Schnittstellen mit Postman untersuchen', 'Projektwissen über mehrere Phasen dokumentieren'] },
    { title: 'Programmieren 2 · Java', summary: 'In der gefilterten Java-Ansicht liegt bisher eine kurze Notiz zur Fail-fast-Methode im Java-Projekt. Ein ausführlicher Themenrückblick ist dort noch nicht dokumentiert.', topics: ['Fail-fast-Methode im Java-Projekt'], view: '374a49695fb880bab161000c78245bd9' },
    { title: 'Digitaltechnik', summary: 'Wie stellt ein Rechner Zahlen dar und wie rechnet er damit? Meine Lernnotizen und die Klausurvorbereitung behandeln Zahlensysteme, binäre Arithmetik und das Zweierkomplement.', topics: ['Stellenwertsysteme und b-adische Darstellung', 'Binäre Arithmetik', 'Zweierkomplement am 8-Bit-Beispiel', 'Themenübersicht und Übungen zur Klausurvorbereitung'], view: '375a49695fb880cc9246000c995f7ce5' },
  ],
  'praxis-1': [
    { title: 'Daten verstehen', summary: 'Ein Schwerpunkt meiner Praxisnotizen ist die Frage, wie sich Messdaten sinnvoll auswerten lassen. Dazu gehören Datenqualität, geeignete Zeiträume und die Unterscheidung zwischen auffälligen Werten und Messfehlern.', topics: ['Datenqualität und Vorverarbeitung', 'Auswertezeiträume bewusst auswählen', 'Beobachtungen von Annahmen trennen'] },
    { title: 'Fragen klären', summary: 'Offene Fragen an Fachleute und Betreuung sind ein eigener Teil meiner Dokumentation. So lassen sich Annahmen prüfen, bevor eine Auswertung darauf aufbaut.', topics: ['Fachliche Rückfragen vorbereiten', 'Annahmen überprüfen und überarbeiten', 'Erkenntnisse nachvollziehbar festhalten'] },
    { title: 'Arbeit strukturieren', summary: 'Arbeitsplan, Auswertungsansatz und Dokumentation gehören zusammen. Der Einblick bleibt bei meiner Arbeitsweise; konkrete Unternehmensdaten und Projektinterna sind nicht Teil dieses Rückblicks.', topics: ['Arbeitsschritte planen', 'Auswertungen nachvollziehbar dokumentieren', 'Theorie mit praktischen Fragestellungen verbinden'] },
  ],
};
