import type { MediaName } from './media';

export const chapters: { slug: string; title: string; intro: string; media: MediaName; heading: string; paragraphs: string[]; question: string }[] = [
  { slug: 'flug-ankunft', title: 'Ankunft', intro: 'Hawaii war 2025 das Ziel meiner Sprachreise. Hier beginnt die Geschichte auf Oahu.', media: 'arrival', heading: 'Ein Anfang auf Oahu', paragraphs: ['Diese Reise hatte einen festen Anlaufpunkt: die Sprachschule in Ala Moana. Oahu war damit mehr als eine Station zum Weiterreisen. Die Insel war der Ort für den Alltag während meiner Sprachreise.', 'Zum Hawaii-Aufenthalt gehörte außerdem eine Reise nach Big Island. Die beiden Inseln bekommen hier eigene Kapitel. Dazwischen stehen der Alltag, das Unterwegssein und das Essen.'], question: 'Steven, woran erinnerst du dich beim Ankommen zuerst? Was ist auf dem Weg vom Flug zur Unterkunft tatsächlich passiert?' },
  { slug: 'alltag', title: 'Alltag auf Oahu', intro: 'Eine Sprachschule in Ala Moana. Und die Frage, wie aus einem Reiseziel für eine Weile Alltag wird.', media: 'daily', heading: 'Zwischen Schule und Stadt', paragraphs: ['Meine Sprachreise nach Hawaii führte mich 2025 an eine Sprachschule in Ala Moana auf Oahu. Sie war eine eigenständige Reise, kein Auslandssemester und keine Studienleistung.', 'Dieses Kapitel gehört dem Teil einer Reise, der zwischen den großen Ausflügen liegt. Dem Weg zur Schule, der Stadt und den wiederkehrenden Wegen. Gerade dafür braucht es die kleinen, konkreten Erinnerungen.'], question: 'Wie verlief ein typischer Schultag? Welchen Weg bist du gegangen, wo hast du gern angehalten, und welche Erinnerung verbindest du mit dem Freitagsfeuerwerk?' },
  { slug: 'adventures', title: 'Unterwegs', intro: 'Oahu abseits des Schulalltags. Ein Kapitel für die Wege über die Insel und den Fallschirmsprung.', media: 'adventures', heading: 'Über die Insel hinaus', paragraphs: ['Die Sprachschule in Ala Moana ist der Ausgangspunkt dieser Reisegeschichte. Das Unterwegssein auf Oahu bekommt seinen eigenen Raum: für die Ausflüge, die Wanderungen und den Fallschirmsprung.', 'Der Absprung steht als einzelner Moment im Mittelpunkt. Was davor im Flugzeug und danach am Boden passiert ist, lässt sich aus einem Bild allein nicht erzählen. Diese Erinnerung gehört mir, und sie soll hier in meinen Worten stehen.'], question: 'Welche Wanderung und welche Mietwagenfahrt gehören in dieses Kapitel? Wie hast du den Moment vor dem Absprung und die Landung erlebt?' },
  { slug: 'essen-kultur', title: 'Essen', intro: 'Poke, Foodtrucks und Shave Ice: ein eigenes Kapitel der Hawaii-Reise.', media: 'food', heading: 'Eine Reise geht auch durch den Alltag', paragraphs: ['Zum Erzählen einer Reise gehören auch die Essenspausen. Hier bekommen die Aufnahmen vom Essen auf Hawaii ihren Platz, zwischen den Wegen durch Oahu und der Reise nach Big Island.', 'Eine kleine Kulturgeschichte braucht mehr als Namen von Gerichten. Sie braucht den konkreten Ort, die Begegnung und den eigenen Eindruck. Dieser Teil wird aus meinen Erinnerungen ergänzt.'], question: 'Welches Gericht ist dir besonders im Gedächtnis geblieben? Wo hast du es gegessen und was war daran neu für dich? Welche Orte kannst du sicher benennen?' },
  { slug: 'big-island', title: 'Big Island', intro: 'Eine andere Insel innerhalb derselben Hawaii-Reise.', media: 'island', heading: 'Der Wechsel der Insel', paragraphs: ['Während meiner Sprachreise nach Hawaii 2025 war ich auch auf Big Island unterwegs. Oahu mit der Sprachschule in Ala Moana und dieser Inselwechsel sind zwei verschiedene Teile der Reise.', 'Für Big Island sind Mauna Kea, eine Lavaröhre, Mantarochen und schwarzer Sand als Themen vorgesehen. Die Reihenfolge und die persönlichen Geschichten dazu bleiben offen, bis die Erinnerungen und Aufnahmen zusammenpassen.'], question: 'In welcher Reihenfolge warst du an diesen Orten? Welche einzelne Erinnerung möchtest du ausführlich erzählen, und was genau hast du beim Nachttauchgang erlebt?' },
];

export const phases = [
  { slug: 'semester-1', title: 'Erste Theoriephase', kind: 'Theorie', intro: 'Der Einstieg an der DHBW Mosbach.', question: 'Welche belegten Module, Aufgaben und eigenen Erkenntnisse möchtest du aus der ersten Theoriephase veröffentlichen? Bitte bestätige auch den Zeitraum.' },
  { slug: 'praxis-1', title: 'Erste Praxisphase', kind: 'Praxis', intro: 'Lernen beim Praxispartner.', question: 'Welche persönliche Erkenntnis aus der ersten Praxisphase darf hier stehen, ohne Projektinhalte, Interna oder den Namen des Praxispartners zu nennen? Welcher Zeitraum ist freigegeben?' },
  { slug: 'semester-2', title: 'Zweite Theoriephase', kind: 'Theorie', intro: 'Zurück an der Hochschule.', question: 'Was hat sich für dich gegenüber der ersten Theoriephase verändert? Welche Studieninhalte und welcher Zeitraum sind für diesen Rückblick bestätigt?' },
];
